services:
  - type: web
    name: doanvien-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn doanvien_site.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: doanvien_site.settings
      - key: PYTHON_VERSION
        value: 3.10
