# Generated by Django 5.2 on 2025-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doanvien', '0002_group_alter_member_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='note',
            field=models.CharField(blank=True, choices=[('Tổ trưởng', 'Tổ trưởng'), ('Tổ phó', 'Tổ phó'), ('Người lao động', 'Người lao động')], max_length=50, null=True),
        ),
    ]
